In [1]:
import numpy as np 
import pandas as pd
from IPython.display import display

match=pd.read_csv('..//Data/matches.csv')
delivery=pd.read_csv('../Data/deliveries.csv')

display(match.head())
display(match.shape)

display(delivery.head())
display(delivery.shape)

total_score_df=delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()
# First inning total
total_score_df=total_score_df[total_score_df['inning']==1]
# ---display(total_score_df)

# Merging the total score to match df  
match_df=match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')
# ---display(match_df)
display(match_df.shape)

# this data is from 2008 so some teams are changed and some are not playing so we will remove them or replace them 
match['team1'].unique()

teams=['Sunrisers Hyderabad',
       'Mumbai Indians',
       'Royal Challengers Bangalore',
       'Kolkata Knight Riders',
       'Kings XI Punjab',
       'Chennai Super Kings',
       'Rajasthan Royals',
       'Delhi Capitals'
       ]
# Replacing the names of teams cause their name is changed now 
# in match_df
match_df['team1']=match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2']=match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team1']=match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2']=match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

# you know well that purane team ke names delivery me the to unhe bhi replace krna hoga 
delivery['batting_team'] = delivery['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')
delivery['batting_team'] = delivery['batting_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')


# after replacing current team from old team now we have to do one more thing
# in teams column we will remove those who are not playing right now
match_df=match_df[match_df['team1'].isin(teams)]
match_df=match_df[match_df['team2'].isin(teams)]
display(match_df)
display(match_df.shape)

# lets check in how many matches the D/L rule was applied
display(match_df['dl_applied'].value_counts())
# so we will remove all the matches in which D/L was applied because they are not useful for us 
match_df=match_df[match_df["dl_applied"]==0]
match_df = match_df[['match_id','city','winner','total_runs']]

#now we will merge all the data to delivery to get these
delivery_df=match_df.merge(delivery,on='match_id')

# we are building a model that predicts in second innings so we will remove 1st innings from delivery_df
delivery_df=delivery_df[delivery_df['inning']==2]
display(delivery_df.shape)
#to build our model we have the data column that are: batting team,bowling team, city,runs left,balls left, wickets left,total runs ,current rr, required rr, result
""" lets get them """

# finding current score
delivery_df['current_score']=delivery_df.groupby('match_id')['total_runs_y'].cumsum()

# lets move to find runs left : to find this we just simply do total_runs - Current_Score
delivery_df['runs_left']=delivery_df['total_runs_x'] - delivery_df['current_score']


""">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Making some change like instead of total_run_x i want to use "Target"
balls left ki jagah Overs left
"""
# delivery_df['Target']=delivery_df['total_runs_x']
# delivery_df['balls_left']=126-(delivery_df['over']*6+delivery_df['ball'])
# over=(delivery_df['balls_left'])//6
# remaining_balls=(delivery_df['balls_left'])%6
# Overs_left=over.astype(str)+"."+remaining_balls.astype(str)
# delivery_df['Overs_left']=Overs_left
# delivery_df['Final_Score']= delivery_df.groupby('match_id')['Current_Score'].transform('max')

""">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"""

# lets find out balls left
delivery_df['balls_left']=126-(delivery_df['over']*6+delivery_df['ball'])

#lets find out wickets left
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna('0')
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")
delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')
wicket=delivery_df.groupby('match_id')['player_dismissed'].cumsum()
delivery_df['wickets_left']=10-wicket

# lets find out current run rate
delivery_df['current_rr']=(delivery_df['current_score']) / ((120-delivery_df['balls_left'])/6)
# now lets move to required run rate
delivery_df['required_rr']=(delivery_df['runs_left'])/((delivery_df['balls_left'])/6)
# result
def result(row):
    if row['batting_team']==row['winner']:
        return 1
    else:
        return 0
delivery_df['result']=delivery_df.apply(result,axis=1)
# delivery_df['result']=delivery_df['result'].map({1:'Won',0:'Lost'})
display(delivery_df)

final_df=delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','total_runs_x',
                     'wickets_left','current_score','current_rr','required_rr','result']]

# shuffling the data for best output of model
final_df=final_df.sample(final_df.shape[0])
display(final_df)

display(final_df.sample())
display(match_df.shape)
display(delivery_df.shape)
display(match.shape)
final_df=final_df.sample(final_df.shape[0])
display(final_df.sample())

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

(756, 18)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

(179078, 21)

(756, 20)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,178
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,8,148
9,10,IPL-2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,10,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,143
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,136
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,171
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,155
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,152

(641, 20)

dl_applied
0    626
1     15
Name: count, dtype: int64

(72413, 24)

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets_left,current_rr,required_rr,result
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,NaN,NaN,1,206,119,10,6.000000,10.386555,0
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,NaN,NaN,1,206,118,10,3.000000,10.474576,0
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,NaN,NaN,1,206,117,10,2.000000,10.564103,0
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,NaN,NaN,3,204,116,10,4.500000,10.551724,0
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,NaN,NaN,7,200,115,10,8.400000,10.434783,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149573,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,NaN,NaN,152,0,4,5,7.862069,0.000000,0
149574,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,NaN,NaN,154,-2,3,5,7.897436,-4.000000,0
149575,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,1,run out,KH Pandya,155,-3,2,4,7.881356,-9.000000,0
149576,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,NaN,NaN,157,-5,1,4,7.915966,-30.000000,0
149577,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,1,lbw,NaN,157,-5,0,3,7.850000,-inf,0

,batting_team,bowling_team,city,runs_left,balls_left,total_runs_x,wickets_left,current_score,current_rr,required_rr,result
121369,Royal Challengers Bangalore,Sunrisers Hyderabad,Bangalore,202,113,208,10,6,5.142857,10.725664,0
54266,Delhi Capitals,Sunrisers Hyderabad,Hyderabad,83,54,175,6,92,8.363636,9.222222,0
148819,Mumbai Indians,Chennai Super Kings,Chennai,17,28,136,6,119,7.760870,3.642857,1
122395,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,52,68,133,9,81,9.346154,4.588235,1
101707,Sunrisers Hyderabad,Chennai Super Kings,Chennai,67,13,209,5,142,7.962617,30.923077,0
...,...,...,...,...,...,...,...,...,...,...,...
4878,Delhi Capitals,Sunrisers Hyderabad,Delhi,84,54,185,8,101,9.181818,9.333333,0
132698,Kings XI Punjab,Mumbai Indians,Mumbai,145,87,197,9,52,9.454545,10.000000,0
88402,Delhi Capitals,Chennai Super Kings,Abu Dhabi,169,107,177,9,8,3.692308,9.476636,0
79437,Rajasthan Royals,Royal Challengers Bangalore,Jaipur,167,118,171,10,4,12.000000,8.491525,1
6534,Kolkata Knight Riders,Mumbai Indians,Kolkata,60,50,173,5,113,9.685714,7.200000,0

,batting_team,bowling_team,city,runs_left,balls_left,total_runs_x,wickets_left,current_score,current_rr,required_rr,result
32488,Sunrisers Hyderabad,Royal Challengers Bangalore,Centurion,157,107,170,10,13,6.0,8.803738,0

(626, 4)

(72413, 31)

(756, 18)

,batting_team,bowling_team,city,runs_left,balls_left,total_runs_x,wickets_left,current_score,current_rr,required_rr,result
3352,Delhi Capitals,Mumbai Indians,Mumbai,61,38,142,4,81,5.926829,9.631579,0

In [14]:
# ------------------Training the Model----------------------
""" there is an issue i.e. the data set final_df is too large to train the model it takes more and more time lets reduce"""
# data cleaning: 
# final_df.replace([np.inf,-np.inf],np.nan,inplace=True)
# final_df.dropna(inplace=True)
# sample_df=final_df.sample(frac=0.1,random_state=1)
# feature and target split 
final_df=final_df[final_df['balls_left']!=0]
x=final_df.iloc[:,:-1] # till last column (except last line)
y=final_df.iloc[:,-1] # takes only last line 
from sklearn.model_selection import train_test_split # this function helps to divide dataset into two parts: 1: training set 2: test set  
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
display(x_train.shape)
from sklearn.compose import ColumnTransformer
# columnTransformer use : Which columns to transform .How to transform them . What to do with the remaining columns
from sklearn.preprocessing import OneHotEncoder
# trf is name of variable that is columntransformer 
trf=ColumnTransformer([('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])],remainder='passthrough')
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
# Pipeline ? : This imports the Pipeline class, which allows you to combine multiple preprocessing and modeling steps into a single streamlined object
# model pipeline 
pipe=Pipeline(steps=[('step1',trf),
                     ('step2',LogisticRegression(solver='liblinear'))])
# step 1 encoding /// step 2 apply logistic regression 
# final_df.isnull().sum()
final_df.dropna(inplace=True)
display(x_train.describe()) # required run rate is stands from -infinity to +inf because of jab runs chahiye aur ball na bachi ho.
# model training 
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
# model evaluation
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
display(f" Accuracy of the model is : {acc*100:.2f} %")

(49939, 10)

,runs_left,balls_left,total_runs_x,wickets_left,current_score,current_rr,required_rr
count,49939.000000,49939.000000,49939.000000,49939.000000,49939.000000,49939.000000,49939.000000
mean,92.611866,62.850778,165.746951,7.553435,73.135085,7.450346,10.347520
std,49.920566,33.239133,29.251016,2.122996,46.701120,2.278776,13.753540
min,-16.000000,-2.000000,65.000000,0.000000,0.000000,0.000000,-510.000000
25%,53.000000,35.000000,147.000000,6.000000,34.000000,6.264706,7.146067
50%,92.000000,63.000000,165.000000,8.000000,70.000000,7.500000,8.888889
75%,130.000000,92.000000,185.000000,9.000000,108.000000,8.696629,10.891304
max,249.000000,119.000000,250.000000,10.000000,222.000000,42.000000,678.000000

' Accuracy of the model is : 81.57 %'

In [15]:
# --- Function Definition ---
def match_progress(x_df, match_id, pipe):
    match = x_df[x_df['match_id'] == match_id]
    match = match[(match['ball'] == 6)]

    # If match_id not found, stop gracefully
    if match.empty:
        print(f"No data found for match_id = {match_id}")
        return None, None

    temp_df = match[['batting_team', 'bowling_team', 'city', 'runs_left', 'balls_left',
                     'wickets_left', 'total_runs_x', 'current_score', 'current_rr', 'required_rr']]
    temp_df = temp_df[temp_df['balls_left'] != 0]

    # Model prediction
    result = pipe.predict_proba(temp_df)
    temp_df['lose'] = np.round(result.T[0] * 100, 1)
    temp_df['win'] = np.round(result.T[1] * 100, 1)
    temp_df['end_of_over'] = range(1, temp_df.shape[0] + 1)

    # Target and progress tracking
    target = temp_df['total_runs_x'].values[0]
    runs = list(temp_df['runs_left'].values)
    new_runs = runs[:]
    runs.insert(0, target)
    temp_df['runs_after_over'] = np.array(runs)[:-1] - np.array(new_runs)

    wickets = list(temp_df['wickets_left'].values)
    new_wickets = wickets[:]
    new_wickets.insert(0, 10)
    wickets.append(0)

    w = np.array(wickets)
    nw = np.array(new_wickets)
    temp_df['wickets_in_over'] = (nw - w)[:temp_df.shape[0]]

    print("Target:", target)
    temp_df = temp_df[['end_of_over', 'runs_after_over', 'wickets_in_over', 'lose', 'win']]
    return temp_df, target


# --- USER INPUT SECTION ---
try:
    match_id = int(input("Enter any match_id to view prediction: "))
    temp_df, target = match_progress(delivery_df, match_id, pipe)

    if temp_df is not None:
        display(temp_df)
except ValueError:
    print("Invalid input. Please enter a valid integer.")

Target: 171

        end_of_over  runs_after_over  wickets_in_over  lose   win
112148            1                7                0  62.1  37.9
112154            2                5                0  61.6  38.4
112160            3                8                0  57.6  42.4
112166            4                9                0  52.3  47.7
112172            5                8                0  48.1  51.9
112179            6                9                2  71.1  28.9
112186            7                8                0  67.5  32.5
112192            8                4                0  68.3  31.7
112200            9                9                0  63.4  36.6
112206           10                7                0  60.8  39.2
112212           11               14                1  63.7  36.3
112218           12                8                0  59.8  40.2
112224           13               10                0  53.3  46.7
112230           14                5                0  53.2  46.8
112238           15               11                1  60.0  40.0
112244           16                8                1  70.0  30.0
112250           17               14                0  58.6  41.4
112256           18                7                1  70.2  29.8
112262           19                9                0  66.3  33.7