In [2]:
import numpy as np 
import pandas as pd
from IPython.display import display

match=pd.read_csv('..//Data/matches.csv')
delivery=pd.read_csv('../Data/deliveries.csv')

display(match.head())
display(match.shape)

display(delivery.head())
display(delivery.shape)

total_score_df=delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()
# First inning total
total_score_df=total_score_df[total_score_df['inning']==1]
# ---display(total_score_df)

match_df=match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')
# ---display(match_df)
display(match_df.shape)

# this data is from 2008 so some teams are changed and some are not playing so we will remove them or replace them 
match['team1'].unique()

teams=['Sunrisers Hyderabad',
       'Mumbai Indians',
       'Royal Challengers Bangalore',
       'Kolkata Knight Riders',
       'Kings XI Punjab',
       'Chennai Super Kings',
       'Rajasthan Royals',
       'Delhi Capitals'
       ]
# Replacing the names of teams cause their name is changed now 
# in match_df
match_df['team1']=match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2']=match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team1']=match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2']=match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

# you know well that purane team ke names delivery me the to unhe bhi replace krna hoga 
delivery['batting_team'] = delivery['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')
delivery['batting_team'] = delivery['batting_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')


# after replacing current team from old team now we have to do one more thing
# in teams column we will remove those who are not playing right now
match_df=match_df[match_df['team1'].isin(teams)]
match_df=match_df[match_df['team2'].isin(teams)]
display(match_df)
display(match_df.shape)

# lets check in how many matches the D/L rule was applied
display(match_df['dl_applied'].value_counts())
# so we will remove all the matches in which D/L was applied because they are not useful for us 
match_df=match_df[match_df["dl_applied"]==0]
match_df = match_df[['match_id','city','winner','total_runs','date']]

#now we will merge all the data to delivery to get these
delivery_df=match_df.merge(delivery,on='match_id')

# we are building a model that predicts in second innings so we will remove 1st innings from delivery_df
delivery_df=delivery_df[delivery_df['inning']==2]
display(delivery_df.shape)
#to build our model we have the data column that are: batting team,bowling team, city,runs left,balls left, wickets left,total runs ,current rr, required rr, result
""" lets get them """
# finding current score
delivery_df['Current_Score']=delivery_df.groupby('match_id')['total_runs_y'].cumsum()

# lets move to find runs left : to find this we just simply do total_runs - Current_Score
delivery_df['runs_left']=delivery_df['total_runs_x'] - delivery_df['Current_Score']


""">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Making some change like instead of total_run_x i want to use "Target"
balls left ki jagah Overs left
"""
delivery_df['Target']=delivery_df['total_runs_x']
delivery_df['balls_left']=126-(delivery_df['over']*6+delivery_df['ball'])
over=(delivery_df['balls_left'])//6
remaining_balls=(delivery_df['balls_left'])%6
Overs_left=over.astype(str)+"."+remaining_balls.astype(str)
delivery_df['Overs_left']=Overs_left
delivery_df['Final_Score']= delivery_df.groupby('match_id')['Current_Score'].transform('max')

""">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"""

# lets find out balls left
delivery_df['balls_left']=126-(delivery_df['over']*6+delivery_df['ball'])

#lets find out wickets left
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna('0')
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")
delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')
wicket=delivery_df.groupby('match_id')['player_dismissed'].cumsum()
delivery_df['wickets_left']=10-wicket

# lets find out current run rate
delivery_df['current_rr']=(delivery_df['Current_Score']) / ((120-delivery_df['balls_left'])/6)
# now lets move to required run rate
delivery_df['required_rr']=(delivery_df['runs_left'])/((delivery_df['balls_left'])/6)
# result
def result(row):
    if row['batting_team']==row['winner']:
        return 1
    else:
        return 0
delivery_df['result']=delivery_df.apply(result,axis=1)
# delivery_df['result']=delivery_df['result'].map({1:'Won',0:'Lost'})
display(delivery_df)

final_df=delivery_df[['batting_team','bowling_team','city','runs_left','Overs_left',
                     'wickets_left','Current_Score','Target','current_rr','required_rr','Final_Score','result','date']]

#shuffling the data for best output of model
# final_df=final_df.sample(final_df.shape[0])
# display(final_df)

# display(final_df.sample())
# display(match_df.shape)
# display(delivery_df.shape)
# display(match.shape)
# final_df=final_df.sample(final_df.shape[0])
# display(final_df.sample())

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

(756, 18)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

(179078, 21)

(756, 20)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,178
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,8,148
9,10,IPL-2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,10,158
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,143
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,136
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,171
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,155
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,152

(641, 20)

dl_applied
0    626
1     15
Name: count, dtype: int64

(72413, 25)

,match_id,city,winner,total_runs_x,date,inning,batting_team,bowling_team,over,ball,...,Current_Score,runs_left,Target,balls_left,Overs_left,Final_Score,wickets_left,current_rr,required_rr,result
125,1,Hyderabad,Sunrisers Hyderabad,207,05-04-2017,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,...,1,206,207,119,19.5,172,10,6.000000,10.386555,0
126,1,Hyderabad,Sunrisers Hyderabad,207,05-04-2017,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,...,1,206,207,118,19.4,172,10,3.000000,10.474576,0
127,1,Hyderabad,Sunrisers Hyderabad,207,05-04-2017,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,...,1,206,207,117,19.3,172,10,2.000000,10.564103,0
128,1,Hyderabad,Sunrisers Hyderabad,207,05-04-2017,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,...,3,204,207,116,19.2,172,10,4.500000,10.551724,0
129,1,Hyderabad,Sunrisers Hyderabad,207,05-04-2017,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,...,7,200,207,115,19.1,172,10,8.400000,10.434783,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149573,11415,Hyderabad,Mumbai Indians,152,12-05-2019,2,Chennai Super Kings,Mumbai Indians,20,2,...,152,0,152,4,0.4,157,5,7.862069,0.000000,0
149574,11415,Hyderabad,Mumbai Indians,152,12-05-2019,2,Chennai Super Kings,Mumbai Indians,20,3,...,154,-2,152,3,0.3,157,5,7.897436,-4.000000,0
149575,11415,Hyderabad,Mumbai Indians,152,12-05-2019,2,Chennai Super Kings,Mumbai Indians,20,4,...,155,-3,152,2,0.2,157,4,7.881356,-9.000000,0
149576,11415,Hyderabad,Mumbai Indians,152,12-05-2019,2,Chennai Super Kings,Mumbai Indians,20,5,...,157,-5,152,1,0.1,157,4,7.915966,-30.000000,0
149577,11415,Hyderabad,Mumbai Indians,152,12-05-2019,2,Chennai Super Kings,Mumbai Indians,20,6,...,157,-5,152,0,0.0,157,3,7.850000,-inf,0

In [3]:
# ------------------Training the Model----------------------
""" there is an issue i.e. the data set final_df is too large to train the model it takes more and more time lets reduce"""
# data cleaning: 
final_df.replace([np.inf,-np.inf],np.nan,inplace=True)
final_df.dropna(inplace=True)
sample_df=final_df.sample(frac=0.1,random_state=1)
# feature and target split 
x=sample_df.iloc[:,:-1] # till last column (except last line)
y=sample_df.iloc[:,-1] # takes only last line 
from sklearn.model_selection import train_test_split # this function helps to divide dataset into two parts: 1: training set 2: test set  
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=1)
display(x_train.shape)
from sklearn.compose import ColumnTransformer
# columnTransformer use : Which columns to transform .How to transform them . What to do with the remaining columns
from sklearn.preprocessing import OneHotEncoder
# trf is name of variable that is columntransformer 
trf=ColumnTransformer([('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])],remainder='passthrough')
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
# Pipeline ? : This imports the Pipeline class, which allows you to combine multiple preprocessing and modeling steps into a single streamlined object
# model pipeline 
pipe=Pipeline(steps=[('step1',trf),
                     ('step2',LogisticRegression(solver='liblinear'))])
# step 1 encoding /// step 2 apply logistic regression 
# final_df.isnull().sum()
sample_df.dropna(inplace=True)
display(x_train.describe()) # required run rate is stands from -infinity to +inf because of jab runs chahiye aur ball na bachi ho.
# model training 
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
# model evaluation
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
display(acc)

C:\Users\faisal\AppData\Local\Temp\ipykernel_5472\2918318977.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.replace([np.inf,-np.inf],np.nan,inplace=True)
C:\Users\faisal\AppData\Local\Temp\ipykernel_5472\2918318977.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

(5707, 12)

,runs_left,wickets_left,Current_Score,Target,current_rr,required_rr,Final_Score,result
count,5707.000000,5707.000000,5707.000000,5707.000000,5707.000000,5707.000000,5707.000000,5707.000000
mean,92.012791,7.522516,73.268617,165.281409,7.466644,10.245177,153.065709,0.457684
std,49.987321,2.128860,46.271656,29.390317,2.269753,11.247157,28.425995,0.498250
min,-8.000000,0.000000,0.000000,65.000000,0.000000,-120.000000,42.000000,0.000000
25%,52.000000,6.000000,35.000000,146.500000,6.272727,7.160477,136.000000,0.000000
50%,92.000000,8.000000,70.000000,165.000000,7.500000,8.892857,154.000000,0.000000
75%,129.000000,9.000000,108.000000,185.000000,8.680851,10.846154,172.000000,1.000000
max,246.000000,10.000000,221.000000,250.000000,24.000000,276.000000,223.000000,1.000000

c:\Users\faisal\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1288: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(

0.7876664330763841