In [7]:
import numpy as np 
import pandas as pd
from IPython.display import display

match=pd.read_csv('..//Data/matches.csv')
delivery=pd.read_csv('../Data/deliveries.csv')

display(match.head())
display(match.shape)

display(delivery.head())
display(delivery.shape)

total_score_df=delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()
# First inning total
total_score_df=total_score_df[total_score_df['inning']==1]
# ---display(total_score_df)

match_df=match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')
# ---display(match_df)
display(match_df.shape)

# this data is from 2008 so some teams are changed and some are not playing so we will remove them or replace them 
match['team1'].unique()

teams=['Sunrisers Hyderabad',
       'Mumbai Indians',
       'Royal Challengers Bangalore',
       'Kolkata Knight Riders',
       'Kings XI Punjab',
       'Chennai Super Kings',
       'Rajasthan Royals',
       'Delhi Capitals'
       ]
# Replacing the names of teams cause their name is changed now 
# in match_df
match_df['team1']=match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2']=match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team1']=match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2']=match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

# you know well that purane team ke names delivery me the to unhe bhi replace krna hoga 
delivery['batting_team'] = delivery['batting_team'].str.replace('Delhi Daredevils','Delhi Capitals')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Delhi Daredevils','Delhi Capitals')
delivery['batting_team'] = delivery['batting_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
delivery['bowling_team'] = delivery['bowling_team'].str.replace('Deccan Chargers','Sunrisers Hyderabad')


# after replacing current team from old team now we have to do one more thing
# in teams column we will remove those who are not playing right now
match_df=match_df[match_df['team1'].isin(teams)]
match_df=match_df[match_df['team2'].isin(teams)]
display(match_df)
display(match_df.shape)

# lets check in how many matches the D/L rule was applied
display(match_df['dl_applied'].value_counts())
# so we will remove all the matches in which D/L was applied because they are not useful for us 
match_df=match_df[match_df["dl_applied"]==0]
match_df = match_df[['match_id','city','winner','total_runs','date']]

#now we will merge all the data to delivery to get these
delivery_df=match_df.merge(delivery,on='match_id')

# we are building a model that predicts in second innings so we will remove 1st innings from delivery_df
delivery_df=delivery_df[delivery_df['inning']==2]
display(delivery_df.shape)
#to build our model we have the data column that are: batting team,bowling team, city,runs left,balls left, wickets left,total runs ,current rr, required rr, result
""" lets get them """
# finding current score
delivery_df['Current_Score']=delivery_df.groupby('match_id')['total_runs_y'].cumsum()

# lets move to find runs left : to find this we just simply do total_runs - Current_Score
delivery_df['runs_left']=delivery_df['total_runs_x'] - delivery_df['Current_Score']


""">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Making some change like instead of total_run_x i want to use "Target"
balls left ki jagah Overs left
"""
delivery_df['Target']=delivery_df['total_runs_x']
delivery_df['balls_left']=126-(delivery_df['over']*6+delivery_df['ball'])
over=(delivery_df['balls_left'])//6
remaining_balls=(delivery_df['balls_left'])%6
Overs_left=over.astype(str)+"."+remaining_balls.astype(str)
delivery_df['Overs_left']=Overs_left
delivery_df['Final_Score']= delivery_df.groupby('match_id')['Current_Score'].transform('max')

""">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"""

# lets find out balls left
delivery_df['balls_left']=126-(delivery_df['over']*6+delivery_df['ball'])

#lets find out wickets left
delivery_df['player_dismissed']=delivery_df['player_dismissed'].fillna('0')
delivery_df['player_dismissed']=delivery_df['player_dismissed'].apply(lambda x:x if x=="0" else "1")
delivery_df['player_dismissed']=delivery_df['player_dismissed'].astype('int')
wicket=delivery_df.groupby('match_id')['player_dismissed'].cumsum()
delivery_df['wickets_left']=10-wicket

# lets find out current run rate
delivery_df['current_rr']=(delivery_df['Current_Score']) / ((120-delivery_df['balls_left'])/6)
# now lets move to required run rate
delivery_df['required_rr']=(delivery_df['runs_left'])/((delivery_df['balls_left'])/6)
# result
def result(row):
    if row['batting_team']==row['winner']:
        return 1
    else:
        return 0
delivery_df['result']=delivery_df.apply(result,axis=1)
delivery_df['result']=delivery_df['result'].map({1:'Won',0:'Lost'})
display(delivery_df)

final_df=delivery_df[['batting_team','bowling_team','city','runs_left','Overs_left',
                     'wickets_left','Current_Score','Target','current_rr','required_rr','Final_Score','result','date']]

#shuffling the data for best output of model
final_df=final_df.sample(final_df.shape[0])
display(final_df)

display(final_df.sample())
display(match_df.shape)
display(delivery_df.shape)
display(match.shape)
final_df=final_df.sample(final_df.shape[0])
display(final_df.sample())

   id    Season       city  ...         umpire1        umpire2 umpire3
0   1  IPL-2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2  IPL-2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3  IPL-2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4  IPL-2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5  IPL-2017  Bangalore  ...             NaN            NaN     NaN

[5 rows x 18 columns]

(756, 18)

   match_id  inning  ... dismissal_kind fielder
0         1       1  ...            NaN     NaN
1         1       1  ...            NaN     NaN
2         1       1  ...            NaN     NaN
3         1       1  ...            NaN     NaN
4         1       1  ...            NaN     NaN

[5 rows x 21 columns]

(179078, 21)

(756, 20)

        id    Season  ... match_id total_runs
0        1  IPL-2017  ...        1        207
4        5  IPL-2017  ...        5        157
6        7  IPL-2017  ...        7        178
7        8  IPL-2017  ...        8        148
9       10  IPL-2017  ...       10        158
..     ...       ...  ...      ...        ...
751  11347  IPL-2019  ...    11347        143
752  11412  IPL-2019  ...    11412        136
753  11413  IPL-2019  ...    11413        171
754  11414  IPL-2019  ...    11414        155
755  11415  IPL-2019  ...    11415        152

[641 rows x 20 columns]

(641, 20)

dl_applied
0    626
1     15
Name: count, dtype: int64

(72413, 25)

        match_id       city  ... required_rr  result
125            1  Hyderabad  ...   10.386555    Lost
126            1  Hyderabad  ...   10.474576    Lost
127            1  Hyderabad  ...   10.564103    Lost
128            1  Hyderabad  ...   10.551724    Lost
129            1  Hyderabad  ...   10.434783    Lost
...          ...        ...  ...         ...     ...
149573     11415  Hyderabad  ...    0.000000    Lost
149574     11415  Hyderabad  ...   -4.000000    Lost
149575     11415  Hyderabad  ...   -9.000000    Lost
149576     11415  Hyderabad  ...  -30.000000    Lost
149577     11415  Hyderabad  ...        -inf    Lost

[72413 rows x 35 columns]

                       batting_team           bowling_team  ... result        date
102169             Rajasthan Royals         Delhi Capitals  ...    Won  12-04-2015
112883  Royal Challengers Bangalore         Delhi Capitals  ...   Lost  17-05-2015
137648               Delhi Capitals  Kolkata Knight Riders  ...    Won  30-03-2019
93223         Kolkata Knight Riders         Delhi Capitals  ...    Won  07-05-2014
60552              Rajasthan Royals         Mumbai Indians  ...   Lost  11-04-2012
...                             ...                    ...  ...    ...         ...
101159               Delhi Capitals    Chennai Super Kings  ...   Lost  09-04-2015
102157             Rajasthan Royals         Delhi Capitals  ...    Won  12-04-2015
7465                Kings XI Punjab    Chennai Super Kings  ...   Lost  19-04-2008
116306               Mumbai Indians         Delhi Capitals  ...   Lost  23-04-2016
101140               Delhi Capitals    Chennai Super Kings  ...   Lost  09-04-2015

[72413 rows x 13 columns]

                batting_team      bowling_team  ... result        date
46058  Kolkata Knight Riders  Rajasthan Royals  ...    Won  17-04-2010

[1 rows x 13 columns]

(626, 5)

(72413, 35)

(756, 18)

           batting_team                 bowling_team  ... result        date
20627  Rajasthan Royals  Royal Challengers Bangalore  ...   Lost  18-04-2009

[1 rows x 13 columns]

In [10]:
display(final_df.sample())
# Training the Model:
# x=final_df.iloc[:,:-1] # till last column (except last line)
y=final_df.iloc[:,-1] # takes only last line 
from sklearn.model_selection import train_test_split # this function helps to divide dataset into two parts: 1: training set 2: test set  
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=1)
X_train
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trf=ColumnTransformer([('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city','result'])],remainder='passthrough')
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe=Pipeline(steps=[('step1',trf),
                     ('step2',LogisticRegression(solver='liblinear'))])
final_df.isnull().sum()

                batting_team     bowling_team  ... result        date
62537  Kolkata Knight Riders  Kings XI Punjab  ...    Won  18-04-2012

[1 rows x 13 columns]

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'